apiVersion: v1
kind: Service
metadata:
  name:  capstone1-service
  namespace: capstone1
spec:
  type: NodePort
  selector:
    app: capstone1
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
